version: 2.1
executors:
  app-executor:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/project



jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - run:
          name: show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app- 
      - run:
          name: install dependencies 
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}
  deploy_to_aws_s3:
    docker:
      - image: circleci/node:13.12.0 
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: show current
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: installing awscli
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y install awscli
            sudo apt-get -y install python-pip python-dev build-essential
      - run:
          name: build 
          command: |
            npm install
            npm run build 
            cd build 
            zip ../build.zip -r *.[^.]*
            echo "build successful"
      - run:
          name: deploy to aws
          command: |
              if ["${CIRCLE_BRANCH}" == "master"]
              then 
                aws --region ${AWS_REGION} s3 sync ~/project/build s3//${AWS_PROD_BUCKET} --delete
              elif ["${CIRCLE_BRANCH"} == "staging"]
              then 
                aws --region ${AWS_REGION} s3 sync ~/project/build s3//${AWS_STAGING_BUCKET} --delete
              else 
                aws --region ${AWS_REGION} s3 sync ~/project/build s3//${AWS_DEV_BUCKET} --delete
              fi
  deploy_to_cloudfront:
    docker:
      - image: circleci/node:13.12.0 
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: show current
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y install awscli
            sudo apt-get -y install python-pip python-dev build-essential
      - run:
          name: build 
          command: |
            npm install
            npm run build 
            cd build 
            zip ../build.zip -r *.[^.]*
            echo "build successful"
      - run:
          name: deploy to cloudfront
          command: |
              aws configure set preview.cloudfront true
              if ["${CIRCLE_BRANCH}" == "master"]
              then 
                aws cloudfront create-invalidation --distribution-id ${PROD_CFD_ID} --paths /\*
                aws --region ${AWS_REGION} s3 sync ~/project/build s3//${AWS_PROD_BUCKET} --delete

              elif ["${CIRCLE_BRANCH" == "staging"]
              then 
                aws cloudfront create-invalidation --distribution-id ${STAGING_CFD_ID} --paths /\*
                aws --region ${AWS_REGION} s3 sync ~/project/build s3//${AWS_STAGING_BUCKET} --delete
              else 
                aws cloudfront create-invalidation --distribution-id ${DEV_CFD_ID} --paths /\*
              fi   
workflows:
  build_and_deploy:
    jobs:
      - build 
      - deploy_to_aws_s3:
          requires:
            - build 
          filters:
            branches:
              only:
                - dev
                - staging 
                - master 
      - deploy_to_cloudfront:
          requires:
            - deploy_to_aws_s3 
          filters:
            branches:
              only:
                - dev
                - staging 
                - master 
                
            

        